#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use App\Build;
use Symfony\Component\Console\Application;
use Symfony\Component\Filesystem\Filesystem;

$buildCommand = new Build(
    new Filesystem(),
);

$application = new Application();
$application->add($buildCommand);
$application->setDefaultCommand('build');
$application->run();
