#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Build;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Build());
$application->setDefaultCommand('build');
$application->run();
